version: '3.8'
services:
  backend:
    container_name: sistemainventario-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./data:/data
      - ./backend/iconos:/app/backend/iconos
      - ./backend/imagenes_articulos:/app/backend/imagenes_articulos
      - ./backups:/backups
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    container_name: sistemainventario-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
